export type ClientLanguage = "ka" | "en";

export const CLIENT_COPY = {
  ka: {
    request: "პროექტის მოთხოვნა", secure: "დაცული ფორმა", heroTitle: "პროექტის შესახებ",
    heroText: "შეავსეთ ფორმა რაც შეიძლება დეტალურად. თქვენი პასუხები დაგვეხმარება ზუსტად გავიგოთ პროექტის მიზანი, მასშტაბი და ტექნიკური საჭიროებები.",
    about: "თქვენ შესახებ", aboutText: "როგორ დაგიკავშირდეთ პროექტთან დაკავშირებით?",
    name: "სახელი და გვარი", fullName: "თქვენი სახელი და გვარი", company: "კომპანია / ორგანიზაცია", companyName: "კომპანიის დასახელება",
    email: "ელფოსტა", emailPlaceholder: "you@example.com", phone: "ტელეფონი",
    projectBasics: "პროექტის შესახებ", projectBasicsText: "მიუთითეთ პროექტის ძირითადი მიმართულება.",
    projectName: "პროექტის სახელი", projectNamePlaceholder: "მაგ.: სასტუმროს დაჯავშნის პლატფორმა",
    building: "რას ქმნით?", description: "პროექტის აღწერა",
    descriptionPlaceholder: "მოგვიყევით პროექტის მიზანზე, სამიზნე მომხმარებლებზე, მთავარ ფუნქციებზე და ბიზნეს-ლოგიკაზე.",
    features: "ფუნქციები და ინტეგრაციები", featuresText: "მიუთითეთ ცნობილი მოთხოვნები. თითო ფუნქციის ცალკე ხაზზე მითითება სასურველია.",
    mainFeatures: "ძირითადი ფუნქციები",
    featurePlaceholder: "მომხმარებლის რეგისტრაცია\nპროდუქტების კატალოგი\nდაჯავშნის კალენდარი\nადმინისტრაციული პანელი",
    scope: "უკვე განსაზღვრული მოთხოვნები",
    timing: "ვადები და დამატებითი ინფორმაცია", timingText: "მიუთითეთ ყველაფერი, რაც დაგეგმვას ან მიწოდების ვადას შეიძლება შეეხოს.",
    deadline: "სასურველი დასრულების ვადა", budget: "სასურველი ბიუჯეტი", optional: "არასავალდებულო",
    other: "კიდევ რა უნდა ვიცოდეთ?", otherPlaceholder: "რეფერენსები, კონკურენტები, სასურველი ტექნოლოგია, არსებული სისტემა ან სხვა მნიშვნელოვანი დეტალები.",
    ready: "მზად ხართ გასაგზავნად?", readyText: "თქვენი პასუხები გამოყენებული იქნება პროექტის ტექნიკური მოთხოვნების მოსამზადებლად.",
    sending: "იგზავნება...", send: "მოთხოვნის გაგზავნა", sent: "მოთხოვნა გაიგზავნა", thank: "გმადლობთ",
    sentText: "თქვენი პროექტის მოთხოვნა წარმატებით მივიღეთ. ჩვენი გუნდი გაეცნობა დეტალებს და საჭიროების შემთხვევაში დაგიკავშირდებათ.",
    received: "თქვენ მიერ მოწოდებული ინფორმაცია უკვე მიღებულია და გადაეცა პროექტის შიდა სამუშაო სივრცეს.",
    footer1: "SKUP Studio • პროექტის მოთხოვნა",
    footer2: "ტექნიკური მოთხოვნები • დაგეგმვა • შეფასება",
    invalid: "მოთხოვნის ბმული არასწორია", invalidText: "გთხოვთ, გამომგზავნელს სთხოვოთ ახალი მოთხოვნის ბმულის შექმნა.",
    requiredError: "გთხოვთ, შეავსოთ ყველა აუცილებელი ველი.", tokenError: "ამ ბმულს მოთხოვნის ტოკენი აკლია.",
    types: {
      Web: ["ვებ-აპლიკაცია", "SaaS, ვებგვერდი, პორტალი ან პლატფორმა"],
      Mobile: ["მობილური აპლიკაცია", "iOS, Android ან ორივე პლატფორმა"],
      WordPress: ["WordPress", "ბიზნეს, საინფორმაციო ან e-commerce ვებგვერდი"],
      Hybrid: ["ვებ + მობილური", "ერთზე მეტი პლატფორმის საერთო პროდუქტი"],
    },
    flags: { Authentication: "ავტორიზაცია და მომხმარებლები", Payments: "გადახდები", "Admin panel": "ადმინისტრაციული პანელი", Notifications: "შეტყობინებები", "External API": "გარე API / ინტეგრაციები", "SEO / Analytics": "SEO / ანალიტიკა" },
  },
  en: {
    request: "Project request", secure: "Secure form", heroTitle: "About the project",
    heroText: "Please complete the form with as much detail as possible. Your answers help us understand the project's goals, scope and technical needs.",
    about: "About you", aboutText: "How should we contact you about this project?", name: "Full name", fullName: "Your full name",
    company: "Company / organization", companyName: "Company name", email: "Email", emailPlaceholder: "you@example.com", phone: "Phone",
    projectBasics: "Project basics", projectBasicsText: "Start with the project's main direction.", projectName: "Project name", projectNamePlaceholder: "e.g. Hotel booking platform",
    building: "What are you building?", description: "Project description", descriptionPlaceholder: "Describe the goal, target users, core functionality and business logic.",
    features: "Features & integrations", featuresText: "List known requirements. One feature per line is recommended.", mainFeatures: "Main features",
    featurePlaceholder: "User registration\nProduct catalog\nBooking calendar\nAdmin dashboard", scope: "Known scope items",
    timing: "Timing & additional context", timingText: "Include anything that may affect planning or delivery.", deadline: "Target deadline", budget: "Preferred budget", optional: "optional",
    other: "Anything else we should know?", otherPlaceholder: "References, competitors, preferred technology, existing systems, constraints or other useful context.",
    ready: "Ready to send?", readyText: "Your answers will be used to prepare the project's technical brief.", sending: "Sending...", send: "Send request", sent: "Request sent", thank: "Thank you",
    sentText: "We have received your project request. Our team will review the details and contact you if needed.",
    received: "The information you provided has been received and added to the internal project workspace.",
    footer1: "SKUP Studio • Project request",
    footer2: "Technical requirements • Planning • Estimation", invalid: "Invalid request link",
    invalidText: "Please ask the sender to generate a new project request link.", requiredError: "Please fill in all required fields.", tokenError: "This link is missing its request token.",
    types: {
      Web: ["Web application", "SaaS, website, portal or platform"], Mobile: ["Mobile application", "iOS, Android or cross-platform"],
      WordPress: ["WordPress", "Business, content or ecommerce site"], Hybrid: ["Web + mobile", "A product spanning multiple platforms"],
    },
    flags: { Authentication: "Authentication & users", Payments: "Payments", "Admin panel": "Admin panel", Notifications: "Notifications", "External API": "External APIs / integrations", "SEO / Analytics": "SEO / analytics" },
  },
} as const;
